'use strict';
// Demonstração estática (GitHub Pages): simula a API do servidor no navegador com dados fictícios.
// Os dados ficam no localStorage de cada navegador. Não há servidor, banco, tempo real ou WhatsApp reais.
(function () {
  window.DEMO_STATIC = true;
  const KEY = 'crm.demo.db.v1';
  const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/, DAY = /^\d{4}-\d{2}-\d{2}$/;
  const OPEN = ['aguardando', 'em_atendimento', 'aguardando_cliente'];
  const STATUS_LABEL = { aguardando: 'Aguardando atendimento', em_atendimento: 'Em atendimento', aguardando_cliente: 'Aguardando cliente', resolvido: 'Resolvido', cancelado: 'Cancelado' };
  const now = () => new Date().toISOString();
  const clone = (o) => JSON.parse(JSON.stringify(o));

  // ---------- Carga inicial: desloca todas as datas para "hoje" ----------
  function shifted(data) {
    const delta = Date.now() - new Date(data.exported_at).getTime();
    const walk = (v) => {
      if (Array.isArray(v)) return v.map(walk);
      if (v && typeof v === 'object') { const o = {}; for (const k of Object.keys(v)) o[k] = walk(v[k]); return o; }
      if (typeof v === 'string') {
        if (ISO.test(v)) return new Date(new Date(v).getTime() + delta).toISOString();
        if (DAY.test(v)) return new Date(new Date(v + 'T12:00:00').getTime() + delta).toISOString().slice(0, 10);
      }
      return v;
    };
    const d = walk(data); d.exported_at = now(); return d;
  }
  let db;
  try { db = JSON.parse(localStorage.getItem(KEY)); } catch (_) { db = null; }
  if (!db || db.version !== 1) { db = shifted(window.DEMO_DATA); db.version = 1; db.whatsapp_messages = []; db.attachments = []; db.audit = db.audit || []; }
  const save = () => { try { localStorage.setItem(KEY, JSON.stringify(db)); } catch (_) { /* sem espaço: segue em memória */ } };
  const nextId = (arr) => arr.reduce((m, x) => Math.max(m, Number(x.id) || 0), 0) + 1;
  let session = null; try { session = JSON.parse(sessionStorage.getItem('crm.demo.user')); } catch (_) { session = null; }
  const user = () => session && db.users.find((u) => u.id === session.id && u.active);
  const isMgr = () => ['admin', 'supervisor'].includes(user().role);
  class ApiError extends Error { constructor(status, data) { super((data && data.error) || 'Erro'); this.status = status; this.data = data || {}; } }
  const fail = (status, error, extra = {}) => { throw new ApiError(status, { error, ...extra }); };
  const need = () => { if (!user()) fail(401, 'Faça login para continuar.'); return user(); };
  const requireRole = (...roles) => { const u = need(); if (!roles.includes(u.role)) fail(403, 'Você não tem permissão para esta ação.'); return u; };
  const audit = (action, entity, id, details = {}) => { db.audit.unshift({ id: nextId(db.audit), user_id: user() ? user().id : null, user_name: user() ? user().name : null, action, entity, entity_id: id == null ? null : String(id), details, ip: '127.0.0.1', created_at: now() }); db.audit = db.audit.slice(0, 300); };
  const notify = (uid, title, body, link) => { if (!uid) return; db.notifications.unshift({ id: nextId(db.notifications), user_id: uid, title, body: body || null, link: link || null, read_at: null, created_at: now() }); if (user() && uid === user().id) UI.toast(`${title}${body ? ': ' + body : ''}`, 'info', 6000); };
  const byId = (arr, id) => arr.find((x) => x.id === Number(id));
  const userName = (id) => { const u = byId(db.users, id); return u ? u.name : null; };
  const settings = () => db.settings;
  const digits = (s) => String(s || '').replace(/\D+/g, '');
  const normPhone = (s) => { let d = digits(s); if (!d) return null; if (d.length === 10 || d.length === 11) d = '55' + d; return d; };
  const sortBy = (arr, key, dir) => arr.sort((a, b) => { const x = a[key], y = b[key]; if (x == null && y == null) return 0; if (x == null) return 1; if (y == null) return -1; const c = typeof x === 'number' ? x - y : String(x).localeCompare(String(y), 'pt-BR'); return dir === 'desc' ? -c : c; });
  const page = (arr, q, def = 50) => { const limit = Math.min(Number(q.limit) || def, 300), p = Math.max(Number(q.page) || 1, 1); return { rows: arr.slice((p - 1) * limit, p * limit), total: arr.length, page: p, limit }; };
  const csv = (rows, cols) => { const esc = (v) => { if (v == null) return ''; let s = Array.isArray(v) ? v.join('|') : String(v); if (/[";\n]/.test(s)) s = '"' + s.replace(/"/g, '""') + '"'; return s; }; return '﻿' + [cols.map((c) => c[1]).join(';'), ...rows.map((r) => cols.map((c) => esc(r[c[0]])).join(';'))].join('\r\n'); };

  // ---------- Atendimentos ----------
  function ticketView(t) {
    const c = byId(db.customers, t.customer_id) || {};
    const awaiting = ['aguardando', 'em_atendimento'].includes(t.status) && (!t.last_agent_message_at || new Date(t.last_customer_message_at || t.opened_at) > new Date(t.last_agent_message_at));
    const due = awaiting ? new Date(new Date(t.last_customer_message_at || t.opened_at).getTime() + settings().response_sla_minutes * 60000).toISOString() : null;
    return { ...t, customer_name: c.name, customer_phone: c.phone, customer_phone_digits: c.phone_digits, customer_company: c.company, customer_email: c.email, customer_tags: c.tags, assignee_name: userName(t.assignee_id), created_by_name: userName(t.created_by),
      awaiting_reply: awaiting, response_due_at: due, response_sla_minutes: settings().response_sla_minutes,
      open_tasks: db.tasks.filter((x) => x.ticket_id === t.id && !x.done_at).length,
      open_opportunities: db.opportunities.filter((o) => o.customer_id === t.customer_id && stage(o.stage_id).kind === 'open').length,
      attachments_count: db.attachments.filter((a) => a.ticket_id === t.id).length };
  }
  const scopeT = (t) => isMgr() || t.assignee_id === user().id || t.assignee_id == null;
  const loadT = (id) => { const t = byId(db.tickets, id); if (!t || !scopeT(t)) fail(404, 'Atendimento não encontrado ou fora do seu escopo.'); return t; };
  function addEvent(t, kind, body, extra = {}) {
    const e = { id: nextId(db.ticket_events), ticket_id: t.id, user_id: extra.user === null ? null : (extra.user || user().id), kind, direction: extra.direction || null, channel: extra.channel || null, body, payload: extra.payload || {}, created_at: now() };
    db.ticket_events.push(e);
    if (kind === 'interaction') {
      const out = extra.direction === 'saida';
      Object.assign(t, { last_message_at: e.created_at, last_message_preview: (body || '').slice(0, 160), last_message_direction: extra.direction });
      if (out) { t.last_agent_message_at = e.created_at; t.unread_count = 0; t.first_response_at = t.first_response_at || e.created_at; } else { t.last_customer_message_at = e.created_at; t.unread_count = (t.unread_count || 0) + 1; }
    }
    t.updated_at = now();
    return { ...e, user_name: userName(e.user_id) };
  }
  function filterTickets(q) {
    const me = user().id;
    let list = db.tickets.filter(scopeT).map(ticketView);
    const v = q.view || '';
    if (v === 'mine') list = list.filter((t) => t.assignee_id === me && OPEN.includes(t.status));
    else if (v === 'queue') list = list.filter((t) => t.status === 'aguardando' && !t.assignee_id);
    else if (v === 'unanswered') list = list.filter((t) => t.awaiting_reply);
    else if (v === 'waiting_customer') list = list.filter((t) => t.status === 'aguardando_cliente');
    else if (v === 'closed') list = list.filter((t) => !OPEN.includes(t.status));
    else if (v === 'open') list = list.filter((t) => OPEN.includes(t.status));
    else if (v === 'overdue') list = list.filter((t) => t.awaiting_reply && new Date(t.response_due_at) < Date.now());
    else if (v === 'follow_up_overdue') list = list.filter((t) => t.follow_up_at && new Date(t.follow_up_at) < Date.now() && OPEN.includes(t.status));
    if (q.status) { const s = String(q.status).split(','); list = list.filter((t) => s.includes(t.status)); } else if (q.open === 'true') list = list.filter((t) => OPEN.includes(t.status));
    if (q.queue === 'true') list = list.filter((t) => t.status === 'aguardando');
    if (q.mine === 'true') list = list.filter((t) => t.assignee_id === me);
    if (q.assignee_id === 'none') list = list.filter((t) => !t.assignee_id); else if (q.assignee_id) list = list.filter((t) => t.assignee_id === Number(q.assignee_id));
    if (q.priority) list = list.filter((t) => t.priority === q.priority);
    if (q.channel) list = list.filter((t) => t.channel === q.channel);
    if (q.customer_id) list = list.filter((t) => t.customer_id === Number(q.customer_id));
    if (q.follow_up === 'pending') list = list.filter((t) => t.follow_up_at && OPEN.includes(t.status));
    if (q.tag) list = list.filter((t) => (t.customer_tags || []).includes(q.tag));
    if (q.q) { const s = q.q.toLowerCase(); list = list.filter((t) => [t.protocol, t.subject, t.customer_name, t.customer_phone, t.customer_company].some((x) => String(x || '').toLowerCase().includes(s))); }
    if (q.from) list = list.filter((t) => t.opened_at >= q.from); if (q.to) list = list.filter((t) => t.opened_at.slice(0, 10) <= q.to);
    const prio = { urgente: 0, alta: 1, normal: 2, baixa: 3 };
    if (q.sort) { const key = q.sort === 'priority' ? 'priority' : q.sort; if (q.sort === 'priority') list.forEach((t) => { t._p = prio[t.priority]; }); sortBy(list, q.sort === 'priority' ? '_p' : key === 'last_message_at' ? 'last_message_at' : key, q.dir); }
    else if (v && v !== 'queue') list.sort((a, b) => new Date(b.last_message_at || b.opened_at) - new Date(a.last_message_at || a.opened_at));
    else list.sort((a, b) => (prio[a.priority] - prio[b.priority]) || (new Date(a.opened_at) - new Date(b.opened_at)));
    return list;
  }
  const counts = () => { const me = user().id; const all = db.tickets.filter(scopeT).map(ticketView); const c = (f) => all.filter(f).length; return {
    queue: c((t) => t.status === 'aguardando' && !t.assignee_id), mine: c((t) => t.assignee_id === me && OPEN.includes(t.status)), unanswered: c((t) => t.awaiting_reply),
    overdue: c((t) => t.awaiting_reply && new Date(t.response_due_at) < Date.now()), waiting_customer: c((t) => t.status === 'aguardando_cliente'), open: c((t) => OPEN.includes(t.status)),
    closed: c((t) => !OPEN.includes(t.status)), follow_up_overdue: c((t) => t.follow_up_at && new Date(t.follow_up_at) < Date.now() && OPEN.includes(t.status)),
    unread: all.filter((t) => t.assignee_id === me || !t.assignee_id).reduce((a, t) => a + (t.unread_count || 0), 0) }; };
  const protocol = () => { const d = new Date(); const n = db.tickets.length + 1; return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${String(n).padStart(6, '0')}`; };
  const pickNext = (team) => { const cands = db.users.filter((u) => u.active && u.available && u.role === 'atendente' && (!team || u.team === team)).sort((a, b) => (a.last_assigned_at || '').localeCompare(b.last_assigned_at || '') || a.id - b.id); const p = cands[0]; if (p) p.last_assigned_at = now(); return p || null; };
  const stopFollowUps = (pred, reason) => db.tasks.filter((x) => !x.done_at && (x.automation_rule_id || x.kind === 'acompanhamento') && pred(x)).forEach((x) => { x.done_at = now(); x.closed_reason = reason; });

  // ---------- Automações ----------
  function runRules(trigger, entity, id, dedupe) {
    for (const r of db.automation_rules.filter((x) => x.active && x.trigger === trigger)) {
      const key = dedupe ? `${entity}:${id}:${dedupe}` : null;
      if (key && db.automation_runs.some((x) => x.rule_id === r.id && x.dedupe_key === key)) continue;
      const t = entity === 'ticket' ? byId(db.tickets, id) : null, o = entity === 'opportunity' ? byId(db.opportunities, id) : null;
      const c = r.conditions || {};
      if (c.channel && t && t.channel !== c.channel) continue; if (c.priority && t && t.priority !== c.priority) continue;
      if (c.stage_id && o && Number(c.stage_id) !== o.stage_id) continue; if (c.pipeline_id && o && Number(c.pipeline_id) !== stage(o.stage_id).pipeline_id) continue;
      const owner = t ? t.assignee_id : o.owner_id; if (r.team) { const ou = byId(db.users, owner); if (ou && ou.team && ou.team !== r.team) continue; }
      const cust = byId(db.customers, t ? t.customer_id : o.customer_id) || {};
      const fill = (s) => String(s || '').replace(/\{cliente\}/g, cust.name || '').replace(/\{protocolo\}/g, t ? t.protocol : '').replace(/\{assunto\}/g, t ? t.subject : '').replace(/\{oportunidade\}/g, o ? o.title : '').replace(/\{etapa\}/g, o ? stage(o.stage_id).name : '');
      const p = r.action_params || {}; let res;
      if (r.action === 'create_task') {
        if (db.tasks.some((x) => x.automation_rule_id === r.id && !x.done_at && (t ? x.ticket_id === t.id : x.opportunity_id === o.id))) res = ['ignorada', 'Já existe uma tarefa aberta criada por esta regra.'];
        else { const title = fill(p.title || 'Acompanhar {cliente}'); const assignee = p.assignee === 'owner' || !p.assignee ? owner : Number(p.assignee); db.tasks.push({ id: nextId(db.tasks), title, description: `Criada automaticamente pela regra "${r.name}".`, customer_id: cust.id, ticket_id: t ? t.id : null, opportunity_id: o ? o.id : null, assignee_id: assignee, due_at: new Date(Date.now() + (Number(p.due_in_days) || 1) * 86400000).toISOString(), priority: p.priority || 'normal', done_at: null, automation_rule_id: r.id, kind: 'acompanhamento', created_by: null, created_at: now(), updated_at: now() }); notify(assignee, 'Tarefa criada por automação', title, '#/tarefas'); res = ['executada', `Tarefa "${title}".`]; }
      } else if (r.action === 'notify') {
        const to = p.to === 'supervisors' ? db.users.filter((u) => u.active && u.role !== 'atendente').map((u) => u.id) : p.to === 'admins' ? db.users.filter((u) => u.active && u.role === 'admin').map((u) => u.id) : p.to === 'owner' || !p.to ? (owner ? [owner] : []) : [Number(p.to)];
        to.forEach((u) => notify(u, fill(p.title || r.name), fill(p.body), t ? `#/atendimentos/${t.id}` : `#/funil/${o.id}`)); res = to.length ? ['executada', `Notificados: ${to.length} usuário(s).`] : ['ignorada', 'Nenhum destinatário.'];
      } else if (r.action === 'distribute') {
        if (!t || t.assignee_id || t.status !== 'aguardando') res = ['ignorada', 'Atendimento já tem responsável ou não está na fila.'];
        else { const pk = pickNext(r.team); if (!pk) res = ['ignorada', 'Nenhum atendente disponível; permanece na fila.']; else { t.assignee_id = pk.id; t.version++; addEvent(t, 'system', `Distribuído automaticamente para ${pk.name} (regra "${r.name}")`, { user: null, payload: { action: 'assigned', to: pk.id, auto: true } }); notify(pk.id, 'Novo atendimento atribuído', `${t.protocol} — ${t.subject}`, `#/atendimentos/${t.id}`); res = ['executada', `Atribuído a ${pk.name}.`]; } }
      } else if (r.action === 'set_priority') { if (!t || t.priority === p.priority) res = ['ignorada', 'Prioridade já era a definida.']; else { t.priority = p.priority; addEvent(t, 'system', `Prioridade alterada para "${p.priority}" (regra "${r.name}")`, { user: null, payload: { action: 'priority' } }); res = ['executada', `Prioridade: ${p.priority}.`]; } }
      else if (r.action === 'add_tag') { if ((cust.tags || []).includes(p.tag)) res = ['ignorada', 'Cliente já tinha a etiqueta.']; else { cust.tags = [...(cust.tags || []), p.tag]; res = ['executada', `Etiqueta "${p.tag}" adicionada.`]; } }
      else res = ['falhou', 'WhatsApp não está conectado; mensagem automática não enviada.'];
      db.automation_runs.unshift({ id: nextId(db.automation_runs), rule_id: r.id, entity, entity_id: id, status: res[0], details: res[1], dedupe_key: key, created_at: now() });
      if (res[0] === 'executada') { r.last_run_at = now(); r.runs_count = (r.runs_count || 0) + 1; }
    }
  }
  function runScheduled() {
    const s = settings();
    for (const t of db.tickets.map(ticketView)) {
      if (t.awaiting_reply && new Date(t.response_due_at) < Date.now()) runRules('ticket_response_overdue', 'ticket', t.id, `overdue:${t.last_customer_message_at || t.opened_at}`);
      if (t.follow_up_at && new Date(t.follow_up_at) < Date.now() && OPEN.includes(t.status)) runRules('ticket_follow_up_overdue', 'ticket', t.id, `followup:${t.follow_up_at}`);
    }
    for (const o of db.opportunities) if (stage(o.stage_id).kind === 'open' && new Date(o.updated_at) < Date.now() - s.idle_opportunity_days * 86400000) runRules('opportunity_idle', 'opportunity', o.id, `idle:${o.updated_at}`);
  }

  // ---------- Funil ----------
  const stage = (id) => byId(db.stages, id) || {};
  function oppView(o) {
    const c = byId(db.customers, o.customer_id) || {}, s = stage(o.stage_id), p = byId(db.pipelines, s.pipeline_id) || {};
    const tks = db.tasks.filter((x) => x.opportunity_id === o.id && !x.done_at);
    const custTk = db.tickets.filter((t) => t.customer_id === o.customer_id);
    const lastContact = db.ticket_events.filter((e) => e.kind === 'interaction' && custTk.some((t) => t.id === e.ticket_id)).map((e) => e.created_at).sort().pop() || null;
    const openT = custTk.filter((t) => OPEN.includes(t.status)).sort((a, b) => b.opened_at.localeCompare(a.opened_at))[0];
    return { ...o, customer_name: c.name, customer_phone: c.phone, customer_email: c.email, customer_company: c.company, customer_source: c.source, customer_tags: c.tags, owner_name: userName(o.owner_id), stage_name: s.name, stage_kind: s.kind, pipeline_id: s.pipeline_id, pipeline_name: p.name,
      open_tasks: tks.length, next_task_at: tks.map((x) => x.due_at).filter(Boolean).sort()[0] || null, last_contact_at: lastContact, open_ticket_id: openT ? openT.id : null, open_ticket_status: openT ? openT.status : null };
  }
  const scopeO = (o) => isMgr() || o.owner_id === user().id || o.owner_id == null;
  const loadO = (id) => { const o = byId(db.opportunities, id); if (!o || !scopeO(o)) fail(404, 'Oportunidade não encontrada ou fora do seu escopo.'); return o; };
  const oppEvent = (o, body, payload = {}) => db.opportunity_events.push({ id: nextId(db.opportunity_events), opportunity_id: o.id, user_id: user().id, body, payload, created_at: now() });

  // ---------- Clientes ----------
  const scopeC = (c) => isMgr() || c.owner_id === user().id || c.owner_id == null || db.tickets.some((t) => t.customer_id === c.id && t.assignee_id === user().id);
  const loadC = (id) => { const c = byId(db.customers, id); if (!c || !scopeC(c)) fail(404, 'Cliente não encontrado ou fora do seu escopo.'); return c; };
  const dups = (phone, email, exclude) => db.customers.filter((c) => c.id !== exclude && ((phone && c.phone_digits === phone) || (email && (c.email || '').toLowerCase() === email))).slice(0, 5).map((c) => ({ id: c.id, name: c.name, phone: c.phone, email: c.email, company: c.company }));
  function custView(c) {
    const tk = db.tickets.filter((t) => t.customer_id === c.id);
    const fu = tk.filter((t) => t.follow_up_at && OPEN.includes(t.status)).map((t) => t.follow_up_at).sort()[0] || null;
    const last = db.ticket_events.filter((e) => e.kind === 'interaction' && tk.some((t) => t.id === e.ticket_id)).map((e) => e.created_at).sort().pop() || null;
    return { ...c, owner_name: userName(c.owner_id), open_tickets: tk.filter((t) => OPEN.includes(t.status)).length, next_follow_up: fu, last_contact_at: last, open_opportunities: db.opportunities.filter((o) => o.customer_id === c.id && stage(o.stage_id).kind === 'open').length };
  }
  const taskView = (t) => { const c = byId(db.customers, t.customer_id), o = byId(db.opportunities, t.opportunity_id), tk = byId(db.tickets, t.ticket_id); return { ...t, assignee_name: userName(t.assignee_id), customer_name: c ? c.name : null, opportunity_title: o ? o.title : null, ticket_protocol: tk ? tk.protocol : null }; };
  const publicUser = (u) => ({ id: u.id, name: u.name, email: u.email, role: u.role, active: u.active, available: u.available });

  // ---------- Relatórios ----------
  function dashboard() {
    const u = need(), mgr = isMgr(), me = u.id, s = settings();
    const T = db.tickets.filter((t) => mgr || t.assignee_id === me || !t.assignee_id).map(ticketView);
    const today = new Date().toDateString(); const isToday = (d) => d && new Date(d).toDateString() === today;
    const m30 = Date.now() - 30 * 86400000;
    const fr = T.filter((t) => t.first_response_at && new Date(t.opened_at) > m30);
    const t = { queue: T.filter((x) => x.status === 'aguardando' && !x.assignee_id).length, unanswered: T.filter((x) => x.awaiting_reply).length, overdue: T.filter((x) => x.awaiting_reply && new Date(x.response_due_at) < Date.now()).length,
      follow_up_overdue: T.filter((x) => x.follow_up_at && new Date(x.follow_up_at) < Date.now() && OPEN.includes(x.status)).length, open: T.filter((x) => OPEN.includes(x.status)).length,
      mine_open: T.filter((x) => x.assignee_id === me && OPEN.includes(x.status)).length, mine_unanswered: T.filter((x) => x.assignee_id === me && x.awaiting_reply).length,
      resolved_today: T.filter((x) => x.status === 'resolvido' && isToday(x.closed_at) && (mgr || x.assignee_id === me)).length, opened_today: T.filter((x) => isToday(x.opened_at)).length,
      fr_samples: fr.length, fr_within_sla: fr.filter((x) => new Date(x.first_response_at) - new Date(x.opened_at) <= s.response_sla_minutes * 60000).length,
      avg_first_response_s: fr.length ? fr.reduce((a, x) => a + (new Date(x.first_response_at) - new Date(x.opened_at)) / 1000, 0) / fr.length : null, sla_minutes: s.response_sla_minutes };
    const O = db.opportunities.filter((o) => mgr || o.owner_id === me || !o.owner_id).map(oppView);
    const month = (d) => d && new Date(d).getMonth() === new Date().getMonth() && new Date(d).getFullYear() === new Date().getFullYear();
    const open = O.filter((o) => o.stage_kind === 'open');
    const o = { open: open.length, open_value: open.reduce((a, x) => a + Number(x.value), 0), no_next_action: open.filter((x) => !x.next_action_at && !x.open_tasks).length,
      overdue: open.filter((x) => (x.next_action_at && new Date(x.next_action_at) < Date.now()) || (x.next_task_at && new Date(x.next_task_at) < Date.now())).length,
      idle: open.filter((x) => new Date(x.updated_at) < Date.now() - s.idle_opportunity_days * 86400000).length, won_month: O.filter((x) => x.stage_kind === 'won' && month(x.closed_at)).length,
      won_month_value: O.filter((x) => x.stage_kind === 'won' && month(x.closed_at)).reduce((a, x) => a + Number(x.value), 0), lost_month: O.filter((x) => x.stage_kind === 'lost' && month(x.closed_at)).length,
      closing_week: open.filter((x) => x.expected_close_date && new Date(x.expected_close_date) <= new Date(Date.now() + 7 * 86400000)).length, idle_days: s.idle_opportunity_days };
    const K = db.tasks.filter((x) => mgr || x.assignee_id === me);
    const tk = { overdue: K.filter((x) => !x.done_at && x.due_at && new Date(x.due_at) < Date.now()).length, today: K.filter((x) => !x.done_at && isToday(x.due_at)).length };
    const my_tasks = db.tasks.filter((x) => x.assignee_id === me && !x.done_at && (!x.due_at || new Date(x.due_at) < new Date(Date.now() + 2 * 86400000))).map(taskView).sort((a, b) => (a.due_at || 'z').localeCompare(b.due_at || 'z')).slice(0, 8).map((x) => ({ ...x, protocol: x.ticket_protocol }));
    const next_contacts = db.tickets.filter((x) => x.follow_up_at && OPEN.includes(x.status) && (mgr || x.assignee_id === me)).map(ticketView).sort((a, b) => a.follow_up_at.localeCompare(b.follow_up_at)).slice(0, 8);
    const team = mgr ? db.users.filter((x) => x.active && x.role === 'atendente').map((x) => { const mine = db.tickets.filter((t2) => t2.assignee_id === x.id).map(ticketView); return { id: x.id, name: x.name, available: x.available, team: x.team, open: mine.filter((t2) => OPEN.includes(t2.status)).length, unanswered: mine.filter((t2) => t2.awaiting_reply).length, resolved_today: mine.filter((t2) => t2.status === 'resolvido' && isToday(t2.closed_at)).length, overdue_tasks: db.tasks.filter((k) => k.assignee_id === x.id && !k.done_at && k.due_at && new Date(k.due_at) < Date.now()).length }; }) : [];
    return { role: u.role, tickets: t, opportunities: o, tasks: tk, my_tasks, next_contacts, team, help: {
      queue: 'Atendimentos com status "Aguardando atendimento" e sem responsável. Situação atual.', unanswered: 'Atendimentos ativos em que a última mensagem é do cliente (ou ainda não houve resposta). Situação atual.',
      overdue: `Sem resposta há mais de ${s.response_sla_minutes} minutos (prazo configurado em Configurações › Empresa).`, follow_up_overdue: 'Atendimentos abertos com retorno agendado para uma data já passada.',
      no_next_action: 'Oportunidades abertas sem data de próxima ação e sem tarefa pendente.', sla: `Percentual de atendimentos dos últimos 30 dias cuja primeira resposta ocorreu dentro de ${s.response_sla_minutes} minutos após a abertura.`,
      won_month: 'Negócios movidos para a etapa "Ganho" no mês atual, pela data de encerramento.', idle: `Oportunidades abertas sem nenhuma atualização há mais de ${s.idle_opportunity_days} dias.` } };
  }
  function summary(q) {
    const u = need(); const assignee = isMgr() ? (q.assignee_id ? Number(q.assignee_id) : null) : u.id;
    const inP = (d) => d && (!q.from || d >= q.from) && (!q.to || d.slice(0, 10) <= q.to);
    let T = db.tickets.map(ticketView).filter((t) => (!assignee || t.assignee_id === assignee) && (!q.source || (byId(db.customers, t.customer_id) || {}).source === q.source) && (!q.channel || t.channel === q.channel) && (!q.status || t.status === q.status));
    const opened = T.filter((t) => inP(t.opened_at)), closed = T.filter((t) => t.closed_at && inP(t.closed_at));
    const avg = (arr, f) => (arr.length ? arr.reduce((a, x) => a + f(x), 0) / arr.length : null);
    const frs = opened.filter((t) => t.first_response_at);
    const group = (arr, key, label) => { const m = {}; arr.forEach((x) => { const k = key(x); m[k] = (m[k] || 0) + 1; }); return Object.entries(m).map(([k, n]) => ({ [label]: k, n })).sort((a, b) => b.n - a.n); };
    let O = db.opportunities.map(oppView).filter((o) => (!assignee || o.owner_id === assignee) && (!q.source || o.customer_source === q.source));
    const oClosed = O.filter((o) => o.closed_at && inP(o.closed_at)), won = oClosed.filter((o) => o.stage_kind === 'won'), lost = oClosed.filter((o) => o.stage_kind === 'lost'), oOpen = O.filter((o) => o.stage_kind === 'open');
    const byAss = {}; opened.forEach((t) => { const k = t.assignee_name || 'Sem responsável'; byAss[k] = byAss[k] || { name: k, assignee_id: t.assignee_id, total: 0, open: 0, resolved: 0 }; byAss[k].total++; if (OPEN.includes(t.status)) byAss[k].open++; if (t.status === 'resolvido') byAss[k].resolved++; });
    return { period: { from: q.from || null, to: q.to || null },
      tickets: { open: opened.filter((t) => OPEN.includes(t.status)).length, waiting: opened.filter((t) => t.status === 'aguardando').length, in_progress: opened.filter((t) => t.status === 'em_atendimento').length, waiting_customer: opened.filter((t) => t.status === 'aguardando_cliente').length, opened: opened.length,
        resolved: closed.filter((t) => t.status === 'resolvido').length, cancelled: closed.filter((t) => t.status === 'cancelado').length, avg_first_response_s: avg(frs, (t) => (new Date(t.first_response_at) - new Date(t.opened_at)) / 1000), first_response_samples: frs.length, avg_resolution_s: avg(closed.filter((t) => t.status === 'resolvido'), (t) => (new Date(t.closed_at) - new Date(t.opened_at)) / 1000) },
      by_assignee: Object.values(byAss).sort((a, b) => b.total - a.total), by_status: group(opened, (t) => t.status, 'status').map((x) => ({ ...x, label: STATUS_LABEL[x.status] })), by_channel: group(opened, (t) => t.channel, 'channel'), by_source: group(opened, (t) => (byId(db.customers, t.customer_id) || {}).source || 'Não informada', 'source'),
      tasks: { overdue: db.tasks.filter((x) => !x.done_at && x.due_at && new Date(x.due_at) < Date.now() && (!assignee || x.assignee_id === assignee)).length },
      opportunities: { open: oOpen.length, open_value: oOpen.reduce((a, o) => a + Number(o.value), 0), won: won.length, won_value: won.reduce((a, o) => a + Number(o.value), 0), lost: lost.length, conversion: won.length + lost.length ? won.length / (won.length + lost.length) : null, decided: won.length + lost.length,
        lost_reasons: group(lost, (o) => o.lost_reason || 'Não informado', 'reason'), by_stage: db.stages.filter((s) => s.active).map((s) => ({ name: s.name, kind: s.kind, n: O.filter((o) => o.stage_id === s.id && (s.kind === 'open' || (o.closed_at && inP(o.closed_at)))).length })).filter((x) => x.n) },
      methodology: { first_response: 'Tempo médio entre a abertura do atendimento e o registro da primeira interação de saída (resposta ao cliente). Considera apenas atendimentos abertos no período que já possuem primeira resposta.', resolution: 'Tempo médio entre a abertura e o encerramento (status Resolvido) dos atendimentos encerrados no período.', conversion: 'Taxa de conversão = negócios ganhos ÷ (ganhos + perdidos) entre as oportunidades encerradas no período.', period: 'Atendimentos são filtrados pela data de abertura; encerrados e negócios ganhos/perdidos pela data de encerramento; tarefas atrasadas consideram a situação atual.' } };
  }

  // ---------- Rotas ----------
  const R = [];
  const on = (method, pattern, fn) => R.push({ method, re: new RegExp('^' + pattern.replace(/:(\w+)/g, '(?<$1>[^/]+)') + '$'), fn });
  const num = (v) => (v === '' || v == null ? null : Number(v));

  on('GET', '/settings/public', () => ({ settings: { name: settings().name, logo_data: settings().logo_data, primary_color: settings().primary_color, accent_color: settings().accent_color, demo_mode: true } }));
  on('GET', '/settings', () => { need(); return { settings: { ...settings(), demo_mode: true }, stages: db.stages, pipelines: db.pipelines, quick_replies: db.quick_replies.filter((q) => q.active), integrations: { smtp: { configured: false }, whatsapp: { configured: false, phone_number_id: null } } }; });
  on('PUT', '/settings', (p, q, b) => { requireRole('admin'); Object.assign(settings(), b, { demo_mode: true, updated_at: now() }); audit('settings_update', 'company_settings', 1, { fields: Object.keys(b) }); return { settings: settings(), message: 'Configurações salvas.' }; });
  on('POST', '/auth/login', (p, q, b) => { const u = db.users.find((x) => x.email.toLowerCase() === String(b.email || '').toLowerCase()); if (!u || b.password !== 'Demo12345') fail(401, 'E-mail ou senha incorretos.'); if (!u.active) fail(401, 'Usuário desativado. Fale com o administrador.'); session = { id: u.id }; sessionStorage.setItem('crm.demo.user', JSON.stringify(session)); u.last_login_at = now(); audit('login', 'user', u.id); return { user: publicUser(u) }; });
  on('POST', '/auth/logout', () => { session = null; sessionStorage.removeItem('crm.demo.user'); return { ok: true }; });
  on('GET', '/auth/me', () => ({ user: publicUser(need()) }));
  on('PUT', '/auth/me/password', (p, q, b) => { need(); if (b.current_password !== 'Demo12345') fail(400, 'Senha atual incorreta.', { fields: { current_password: 'Senha atual incorreta.' } }); return { ok: true, message: 'Na demonstração a senha continua Demo12345.' }; });
  on('PUT', '/auth/me/availability', (p, q, b) => { need().available = b.available; return { ok: true, available: b.available }; });
  on('POST', '/auth/forgot-password', () => ({ ok: true, message: 'Se o e-mail estiver cadastrado, enviaremos as instruções de recuperação.', mail_configured: false }));
  on('POST', '/auth/reset-password', () => fail(400, 'Redefinição de senha não está disponível na demonstração.'));

  on('GET', '/users', (p, q) => { const u = need(); const list = db.users.filter((x) => x.active || (q.include_inactive === 'true' && u.role !== 'atendente')); return { users: u.role === 'admin' ? list : list.map((x) => ({ id: x.id, name: x.name, role: x.role, active: x.active, available: x.available, team: x.team })) }; });
  on('POST', '/users', (p, q, b) => { requireRole('admin'); if (db.users.some((x) => x.email.toLowerCase() === b.email.toLowerCase())) fail(400, 'Já existe um usuário com este e-mail.', { fields: { email: 'E-mail já cadastrado.' } }); const u = { id: nextId(db.users), name: b.name, email: b.email, role: b.role, active: true, available: b.available !== false, team: b.team || null, last_login_at: null, created_at: now() }; db.users.push(u); audit('user_create', 'user', u.id); return { user: u, message: 'Usuário criado com sucesso (senha na demonstração: Demo12345).' }; });
  on('PUT', '/users/:id', (p, q, b) => { requireRole('admin'); const u = byId(db.users, p.id) || fail(404, 'Usuário não encontrado.'); if (b.role && u.id === user().id && b.role !== 'admin') fail(400, 'Você não pode remover seu próprio perfil de administrador.'); delete b.password; Object.assign(u, b); audit('user_update', 'user', u.id); return { user: u, message: 'Usuário atualizado.' }; });
  on('POST', '/users/:id/deactivate', (p, q, b) => { requireRole('admin'); const u = byId(db.users, p.id) || fail(404); if (u.id === user().id) fail(400, 'Você não pode desativar o seu próprio usuário.'); const pend = { tickets: db.tickets.filter((t) => t.assignee_id === u.id && OPEN.includes(t.status)), tasks: db.tasks.filter((t) => t.assignee_id === u.id && !t.done_at), opportunities: db.opportunities.filter((o) => o.owner_id === u.id && stage(o.stage_id).kind === 'open'), customers: db.customers.filter((c) => c.owner_id === u.id) };
    const total = pend.tickets.length + pend.tasks.length + pend.opportunities.length; if (total && !b.transfer_to) fail(409, 'Este usuário possui pendências. Informe para quem transferi-las.', { pending: { tickets: pend.tickets.length, tasks: pend.tasks.length, opportunities: pend.opportunities.length, customers: pend.customers.length } });
    if (b.transfer_to) { pend.tickets.forEach((t) => { t.assignee_id = b.transfer_to; addEvent(t, 'system', 'Atendimento transferido por desativação de usuário', { payload: { action: 'transfer', to: b.transfer_to } }); }); pend.tasks.forEach((t) => { t.assignee_id = b.transfer_to; }); pend.opportunities.forEach((o) => { o.owner_id = b.transfer_to; }); pend.customers.forEach((c) => { c.owner_id = b.transfer_to; }); }
    u.active = false; u.available = false; audit('user_deactivate', 'user', u.id); return { ok: true, message: 'Usuário desativado. O histórico foi preservado.', transferred: { tickets: pend.tickets.length, tasks: pend.tasks.length, opportunities: pend.opportunities.length, customers: pend.customers.length } }; });
  on('POST', '/users/:id/activate', (p) => { requireRole('admin'); const u = byId(db.users, p.id) || fail(404); u.active = true; return { ok: true, message: 'Usuário reativado.' }; });
  on('POST', '/users/:id/reset-link', (p) => { requireRole('admin'); return { link: `${location.origin}${location.pathname}#/redefinir-senha/demo-${p.id}`, message: 'Na demonstração o link é ilustrativo; a senha continua Demo12345.' }; });

  on('GET', '/tickets/counts', () => { need(); return { counts: counts() }; });
  on('GET', '/tickets/export.csv', (p, q) => { need(); const rows = filterTickets(q); return { csv: csv(rows, [['protocol', 'protocolo'], ['customer_name', 'cliente'], ['customer_phone', 'telefone'], ['subject', 'assunto'], ['channel', 'canal'], ['priority', 'prioridade'], ['status', 'status'], ['assignee_name', 'responsavel'], ['opened_at', 'abertura'], ['first_response_at', 'primeira_resposta'], ['closed_at', 'encerramento']]), filename: 'atendimentos.csv' }; });
  on('GET', '/tickets', (p, q) => { need(); const r = page(filterTickets(q), q); return { tickets: r.rows, total: r.total, page: r.page, limit: r.limit }; });
  on('GET', '/tickets/:id', (p) => { need(); const t = loadT(p.id); const c = byId(db.customers, t.customer_id);
    return { ticket: ticketView(t), events: db.ticket_events.filter((e) => e.ticket_id === t.id).map((e) => ({ ...e, user_name: userName(e.user_id) })), tasks: db.tasks.filter((x) => x.ticket_id === t.id).map(taskView).sort((a, b) => (a.done_at ? 1 : 0) - (b.done_at ? 1 : 0)),
      opportunities: db.opportunities.filter((o) => o.customer_id === t.customer_id).map(oppView).sort((a, b) => (b.stage_kind === 'open') - (a.stage_kind === 'open')), attachments: db.attachments.filter((a) => a.ticket_id === t.id), customer: { ...c, owner_name: userName(c.owner_id) },
      customer_tickets: db.tickets.filter((x) => x.customer_id === t.customer_id && x.id !== t.id).sort((a, b) => b.opened_at.localeCompare(a.opened_at)).slice(0, 8), customer_tasks: db.tasks.filter((x) => x.customer_id === t.customer_id && !x.done_at && x.ticket_id !== t.id).map(taskView).slice(0, 10) }; });
  on('POST', '/tickets', (p, q, b) => { const u = need(); if (u.role === 'atendente' && b.assignee_id && b.assignee_id !== u.id) fail(403, 'Atendentes só podem atribuir atendimentos a si mesmos ou deixá-los na fila.'); if (!byId(db.customers, b.customer_id)) fail(400, 'Cliente não encontrado.', { fields: { customer_id: 'Cliente inválido.' } });
    let assignee = b.assignee_id || null, dist = false; if (!assignee && (settings().auto_distribution || b.auto_assign)) { const pk = pickNext(); if (pk) { assignee = pk.id; dist = true; } }
    const t = { id: nextId(db.tickets), protocol: protocol(), customer_id: b.customer_id, subject: b.subject, description: b.description || null, channel: b.channel, priority: b.priority || 'normal', status: 'aguardando', assignee_id: assignee, opened_at: now(), first_response_at: null, closed_at: null, follow_up_at: null, created_by: u.id, version: 1, created_at: now(), updated_at: now(), last_message_at: null, last_message_preview: null, last_message_direction: null, last_customer_message_at: null, last_agent_message_at: null, unread_count: 0 };
    db.tickets.push(t); addEvent(t, 'system', 'Atendimento aberto', { payload: { action: 'created', channel: b.channel } }); if (b.first_message) addEvent(t, 'interaction', b.first_message, { direction: 'entrada', channel: b.channel, payload: { manual: true } });
    if (assignee) { addEvent(t, 'system', dist ? 'Distribuído automaticamente (rodízio)' : 'Responsável atribuído', { payload: { action: 'assigned', to: assignee } }); if (assignee !== u.id) notify(assignee, 'Novo atendimento atribuído', `${t.protocol} — ${t.subject}`, `#/atendimentos/${t.id}`); }
    audit('ticket_create', 'ticket', t.id, { protocol: t.protocol }); runRules('ticket_created', 'ticket', t.id); return { ticket: ticketView(t), message: `Atendimento ${t.protocol} aberto.` }; });
  on('PUT', '/tickets/:id', (p, q, b) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id && t.assignee_id != null) fail(403, 'Somente o responsável pode editar este atendimento.'); if (b.version !== undefined && b.version !== t.version) fail(409, 'Este atendimento foi alterado por outro usuário. Recarregue para ver a versão atual.'); ['subject', 'description', 'channel', 'priority'].forEach((k) => { if (b[k] !== undefined) t[k] = b[k]; }); t.version++; t.updated_at = now(); audit('ticket_update', 'ticket', t.id); return { ticket: ticketView(t), message: 'Atendimento atualizado.' }; });
  on('POST', '/tickets/:id/claim', (p) => { const u = need(); const t = byId(db.tickets, p.id) || fail(404, 'Atendimento não encontrado.'); if (t.assignee_id && t.assignee_id !== u.id) fail(409, `Este atendimento já foi assumido por ${userName(t.assignee_id)}.`); if (t.status !== 'aguardando') fail(409, `Este atendimento não está aguardando (status atual: ${STATUS_LABEL[t.status]}).`); t.assignee_id = u.id; t.status = 'em_atendimento'; t.version++; u.last_assigned_at = now(); addEvent(t, 'system', 'Atendimento assumido', { payload: { action: 'claimed', to: u.id } }); audit('ticket_claim', 'ticket', t.id); return { ticket: ticketView(t), message: 'Você assumiu este atendimento.' }; });
  on('POST', '/tickets/:id/read', (p) => { need(); loadT(p.id).unread_count = 0; return { ok: true }; });
  on('POST', '/tickets/:id/transfer', (p, q, b) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id && t.assignee_id != null) fail(403, 'Somente o responsável ou um supervisor pode transferir este atendimento.'); if (!OPEN.includes(t.status)) fail(409, 'Não é possível transferir um atendimento encerrado. Reabra-o primeiro.'); const to = byId(db.users, b.to_user_id); if (!to || !to.active) fail(400, 'Usuário de destino inválido ou inativo.'); if (to.id === t.assignee_id) fail(400, 'O atendimento já está com este responsável.'); const from = t.assignee_id; t.assignee_id = to.id; if (t.status !== 'aguardando_cliente') t.status = 'em_atendimento'; t.version++; addEvent(t, 'system', `Transferido para ${to.name}${b.reason ? ` — ${b.reason}` : ''}`, { payload: { action: 'transfer', from, to: to.id } }); notify(to.id, 'Atendimento transferido para você', `${t.protocol} — ${t.subject}`, `#/atendimentos/${t.id}`); audit('ticket_transfer', 'ticket', t.id); return { ticket: ticketView(t), message: 'Atendimento transferido.' }; });
  on('POST', '/tickets/:id/release', (p) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id) fail(403, 'Somente o responsável ou um supervisor pode devolver este atendimento à fila.'); const from = t.assignee_id; t.assignee_id = null; t.status = 'aguardando'; t.version++; addEvent(t, 'system', 'Devolvido à fila de espera', { payload: { action: 'released', from } }); audit('ticket_release', 'ticket', t.id); return { ticket: ticketView(t), message: 'Atendimento devolvido à fila.' }; });
  on('POST', '/tickets/:id/status', (p, q, b) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id) fail(403, 'Somente o responsável ou um supervisor pode alterar o status.'); if (!OPEN.includes(t.status)) fail(409, 'Atendimento já encerrado. Use "Reabrir" para continuar.'); if (b.version !== undefined && b.version !== t.version) fail(409, 'Este atendimento foi alterado por outro usuário. Recarregue para ver a versão atual.'); if (!t.assignee_id && b.status !== 'cancelado') fail(409, 'Assuma o atendimento antes de alterar o status.'); const closing = ['resolvido', 'cancelado'].includes(b.status); const from = t.status; t.status = b.status; t.closed_at = closing ? now() : null; if (closing) t.unread_count = 0; t.version++; addEvent(t, 'system', `Status alterado: ${STATUS_LABEL[from]} → ${STATUS_LABEL[b.status]}${b.note ? ` — ${b.note}` : ''}`, { payload: { action: 'status', from, to: b.status } }); if (closing) stopFollowUps((x) => x.ticket_id === t.id, 'Atendimento encerrado'); audit('ticket_status', 'ticket', t.id, { from, to: b.status }); return { ticket: ticketView(t), message: `Status atualizado para "${STATUS_LABEL[b.status]}".` }; });
  on('POST', '/tickets/:id/reopen', (p, q, b) => { need(); const t = loadT(p.id); if (OPEN.includes(t.status)) fail(409, 'Este atendimento já está aberto.'); const act = t.assignee_id && byId(db.users, t.assignee_id)?.active; t.status = act ? 'em_atendimento' : 'aguardando'; if (!act) t.assignee_id = null; t.closed_at = null; t.version++; addEvent(t, 'system', `Atendimento reaberto${b.note ? ` — ${b.note}` : ''}`, { payload: { action: 'reopened' } }); audit('ticket_reopen', 'ticket', t.id); return { ticket: ticketView(t), message: 'Atendimento reaberto.' }; });
  const saveAtts = (t, ev, list) => (list || []).map((a) => { const att = { id: nextId(db.attachments), ticket_id: t.id, event_id: ev.id, name: a.name, mime: a.mime, size: Math.round((a.data.length * 3) / 4), url: a.data, created_at: now() }; db.attachments.push(att); return att; });
  on('POST', '/tickets/:id/notes', (p, q, b) => { need(); const t = loadT(p.id); const e = addEvent(t, 'note', b.body); e.attachments = saveAtts(t, e, b.attachments); return { event: e, message: 'Anotação interna registrada.' }; });
  on('POST', '/tickets/:id/interactions', (p, q, b) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id) fail(403, 'Assuma o atendimento para registrar interações.'); if (!OPEN.includes(t.status)) fail(409, 'Atendimento encerrado. Reabra-o para registrar novas interações.'); const e = addEvent(t, 'interaction', b.body, { direction: b.direction, channel: b.channel, payload: { manual: true } }); e.attachments = saveAtts(t, e, b.attachments); if (b.direction === 'entrada') { if (t.status === 'aguardando_cliente') { t.status = 'em_atendimento'; addEvent(t, 'system', 'Cliente respondeu: status alterado de Aguardando cliente para Em atendimento', { payload: { action: 'status' } }); } stopFollowUps((x) => x.ticket_id === t.id, 'Cliente respondeu'); runRules('ticket_customer_replied', 'ticket', t.id, `reply:${e.id}`); } return { event: e, ticket: ticketView(t), message: 'Interação registrada.' }; });
  on('POST', '/tickets/:id/follow-up', (p, q, b) => { need(); const t = loadT(p.id); if (!isMgr() && t.assignee_id !== user().id) fail(403, 'Somente o responsável pode agendar retorno.'); t.follow_up_at = b.at; db.tasks.filter((x) => x.ticket_id === t.id && !x.done_at && x.kind === 'retorno').forEach((x) => { x.done_at = now(); x.closed_reason = b.at ? 'Retorno reagendado' : 'Agendamento removido'; }); let task = null; if (b.at) { task = { id: nextId(db.tasks), title: `Retorno: ${t.subject} (${t.protocol})`, description: b.note || null, customer_id: t.customer_id, ticket_id: t.id, opportunity_id: null, assignee_id: t.assignee_id || user().id, due_at: b.at, priority: 'alta', done_at: null, kind: 'retorno', created_by: user().id, created_at: now(), updated_at: now() }; db.tasks.push(task); addEvent(t, 'system', `Retorno agendado para ${new Date(b.at).toLocaleString('pt-BR')}${b.note ? ` — ${b.note}` : ''}`, { payload: { action: 'follow_up' } }); } else addEvent(t, 'system', 'Retorno agendado removido', { payload: { action: 'follow_up_cleared' } }); return { ticket: ticketView(t), task, message: b.at ? 'Retorno agendado e tarefa criada.' : 'Agendamento removido.' }; });
  on('POST', '/tickets/distribute', () => { requireRole('admin', 'supervisor'); const queue = db.tickets.filter((t) => t.status === 'aguardando' && !t.assignee_id); let assigned = 0; for (const t of queue) { const pk = pickNext(); if (!pk) break; t.assignee_id = pk.id; t.version++; addEvent(t, 'system', `Distribuído automaticamente (rodízio) para ${pk.name}`, { payload: { action: 'assigned', to: pk.id, auto: true } }); notify(pk.id, 'Novo atendimento atribuído', `${t.protocol} — ${t.subject}`, `#/atendimentos/${t.id}`); assigned++; } const remaining = queue.length - assigned; audit('tickets_distribute', 'ticket', null, { assigned, remaining }); return { assigned, remaining, message: assigned === 0 ? (remaining === 0 ? 'Não há atendimentos na fila.' : 'Nenhum atendente disponível. Os atendimentos permanecem na fila.') : `${assigned} atendimento(s) distribuído(s).${remaining ? ` ${remaining} permanecem na fila.` : ''}` }; });

  on('GET', '/customers/export.csv', () => { need(); return { csv: csv(db.customers.filter(scopeC), [['id', 'id'], ['name', 'nome'], ['phone', 'telefone'], ['email', 'email'], ['company', 'empresa'], ['city', 'cidade'], ['source', 'origem'], ['tags', 'etiquetas']]), filename: 'clientes.csv' }; });
  on('GET', '/customers/check-duplicates', (p, q) => { need(); return { duplicates: dups(normPhone(q.phone), (q.email || '').trim().toLowerCase() || null, Number(q.exclude_id) || 0) }; });
  on('GET', '/customers', (p, q) => { need(); let list = db.customers.filter(scopeC).map(custView);
    if (q.q) { const s = q.q.toLowerCase(), d = digits(q.q); list = list.filter((c) => [c.name, c.email, c.company].some((x) => String(x || '').toLowerCase().includes(s)) || (d && ((c.phone_digits || '').includes(d) || (c.document || '').includes(d)))); }
    if (q.source) list = list.filter((c) => c.source === q.source); if (q.owner_id) list = list.filter((c) => c.owner_id === Number(q.owner_id)); if (q.tag) list = list.filter((c) => (c.tags || []).includes(q.tag));
    if (q.pending_followup === 'true') list = list.filter((c) => c.next_follow_up); if (q.no_open_ticket === 'true') list = list.filter((c) => !c.open_tickets);
    if (q.sort) sortBy(list, q.sort, q.dir); else list.sort((a, b) => b.updated_at.localeCompare(a.updated_at));
    const r = page(list, q, 25); return { customers: r.rows, total: r.total, page: r.page, limit: r.limit }; });
  on('POST', '/customers/import', (p, q, b) => { requireRole('admin', 'supervisor'); const lines = b.csv.split(/\r?\n/).filter((l) => l.trim()); const sep = (lines[0].match(/;/g) || []).length >= (lines[0].match(/,/g) || []).length ? ';' : ','; const H = { nome: 'name', name: 'name', telefone: 'phone', phone: 'phone', email: 'email', 'e-mail': 'email', empresa: 'company', cidade: 'city', origem: 'source', etiquetas: 'tags', observacoes: 'notes' }; const head = lines[0].split(sep).map((h) => H[h.trim().toLowerCase()] || null); if (!head.includes('name')) fail(400, 'Coluna obrigatória ausente: "nome".');
    const rows = lines.slice(1).map((l, i) => { const rec = {}; l.split(sep).forEach((v, j) => { if (head[j]) rec[head[j]] = v.trim(); }); const errors = []; if (!rec.name || rec.name.length < 2) errors.push('Nome obrigatório.'); const pd = normPhone(rec.phone); if (rec.phone && !pd) errors.push('Telefone inválido.'); const d = errors.length ? [] : dups(pd, (rec.email || '').toLowerCase() || null, 0); return { line: i + 2, data: { ...rec, phone_digits: pd, tags: rec.tags ? rec.tags.split(/[|,]/).map((x) => x.trim()).filter(Boolean) : [] }, errors, warnings: d.length ? [`Possível duplicidade com: ${d.map((x) => `#${x.id} ${x.name}`).join(', ')}`] : [], duplicate: d.length > 0 }; });
    const valid = rows.filter((r) => !r.errors.length); if (!b.commit) return { preview: true, total: rows.length, valid: valid.length, invalid: rows.length - valid.length, duplicates: rows.filter((r) => r.duplicate).length, rows };
    let imported = 0, skipped = 0; valid.forEach((r) => { if (b.skip_duplicates && r.duplicate) { skipped++; return; } db.customers.push({ id: nextId(db.customers), name: r.data.name, phone: r.data.phone || null, phone_digits: r.data.phone_digits, email: r.data.email || null, company: r.data.company || null, city: r.data.city || null, document: null, source: r.data.source || null, tags: r.data.tags, notes: r.data.notes || null, owner_id: null, created_by: user().id, version: 1, created_at: now(), updated_at: now() }); imported++; });
    audit('customers_import', 'customer', null, { imported, skipped }); return { preview: false, imported, skipped, invalid: rows.length - valid.length, errors: rows.filter((r) => r.errors.length).map((r) => ({ line: r.line, errors: r.errors })), message: `${imported} cliente(s) importado(s).` }; });
  on('GET', '/customers/:id', (p) => { need(); const c = loadC(p.id); const tk = db.tickets.filter((t) => t.customer_id === c.id).map(ticketView).sort((a, b) => b.opened_at.localeCompare(a.opened_at));
    return { customer: { ...c, owner_name: userName(c.owner_id) }, tickets: tk, opportunities: db.opportunities.filter((o) => o.customer_id === c.id).map(oppView).sort((a, b) => (b.stage_kind === 'open') - (a.stage_kind === 'open')), tasks: db.tasks.filter((t) => t.customer_id === c.id).map(taskView).sort((a, b) => (a.done_at ? 1 : 0) - (b.done_at ? 1 : 0)), notes: db.customer_notes.filter((n) => n.customer_id === c.id).map((n) => ({ ...n, user_name: userName(n.user_id) })).reverse(), whatsapp_messages: [],
      timeline: db.ticket_events.filter((e) => e.kind !== 'system' && tk.some((t) => t.id === e.ticket_id)).map((e) => ({ ...e, user_name: userName(e.user_id), protocol: tk.find((t) => t.id === e.ticket_id).protocol })).sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, 40), duplicates: dups(c.phone_digits, c.email ? c.email.toLowerCase() : null, c.id) }; });
  const cleanC = (b) => { const o = { ...b }; if (o.email === '') o.email = null; if (o.phone !== undefined) o.phone_digits = normPhone(o.phone); return o; };
  on('POST', '/customers', (p, q, b) => { const u = need(); const d = cleanC(b); const dd = dups(d.phone_digits, (d.email || '').toLowerCase() || null, 0); if (dd.length && !q.force) fail(409, 'Já existe um cliente com este telefone ou e-mail.', { duplicates: dd, can_force: true }); const c = { id: nextId(db.customers), name: d.name, phone: d.phone || null, phone_digits: d.phone_digits || null, email: d.email || null, company: d.company || null, city: d.city || null, document: d.document || null, source: d.source || null, tags: d.tags || [], notes: d.notes || null, owner_id: d.owner_id === undefined ? (u.role === 'atendente' ? u.id : null) : d.owner_id, created_by: u.id, version: 1, created_at: now(), updated_at: now() }; db.customers.push(c); audit('customer_create', 'customer', c.id); return { customer: c, message: 'Cliente cadastrado com sucesso.', duplicates: dd }; });
  on('PUT', '/customers/:id', (p, q, b) => { need(); const c = loadC(p.id); const d = cleanC(b); if (d.version !== undefined && d.version !== c.version) fail(409, 'Este cliente foi alterado por outro usuário. Recarregue a página para ver a versão atual.'); const ph = d.phone !== undefined ? d.phone_digits : c.phone_digits, em = d.email !== undefined ? d.email : c.email; const dd = dups(ph, em ? em.toLowerCase() : null, c.id); if (dd.length && !q.force && (d.phone !== undefined || d.email !== undefined)) fail(409, 'Já existe outro cliente com este telefone ou e-mail.', { duplicates: dd, can_force: true }); delete d.version; Object.assign(c, d, { version: c.version + 1, updated_at: now() }); audit('customer_update', 'customer', c.id); return { customer: c, message: 'Cliente atualizado.' }; });
  on('DELETE', '/customers/:id', (p) => { requireRole('admin'); const c = loadC(p.id); if (db.tickets.some((t) => t.customer_id === c.id) || db.opportunities.some((o) => o.customer_id === c.id)) fail(409, 'Este cliente possui atendimentos ou oportunidades e não pode ser excluído. O histórico deve ser preservado.'); db.customers = db.customers.filter((x) => x.id !== c.id); return { ok: true, message: 'Cliente excluído.' }; });
  on('POST', '/customers/:id/notes', (p, q, b) => { need(); const c = loadC(p.id); const n = { id: nextId(db.customer_notes), customer_id: c.id, user_id: user().id, body: b.body, created_at: now(), user_name: user().name }; db.customer_notes.push(n); c.updated_at = now(); return { note: n, message: 'Anotação adicionada.' }; });

  on('GET', '/opportunities/export.csv', () => { need(); return { csv: csv(db.opportunities.filter(scopeO).map(oppView), [['id', 'id'], ['title', 'titulo'], ['customer_name', 'cliente'], ['owner_name', 'responsavel'], ['pipeline_name', 'funil'], ['stage_name', 'etapa'], ['value', 'valor'], ['next_action', 'proxima_acao'], ['expected_close_date', 'previsao_fechamento'], ['lost_reason', 'motivo_perda']]), filename: 'oportunidades.csv' }; });
  on('GET', '/opportunities', (p, q) => { need(); const pipelines = db.pipelines.filter((x) => x.active); let pid = q.pipeline_id ? Number(q.pipeline_id) : null; if (!pid && !q.all_pipelines) pid = (pipelines.find((x) => x.is_default) || pipelines[0] || {}).id || null;
    let list = db.opportunities.filter(scopeO).map(oppView); if (pid) list = list.filter((o) => o.pipeline_id === pid);
    if (q.owner_id === 'none') list = list.filter((o) => !o.owner_id); else if (q.owner_id) list = list.filter((o) => o.owner_id === Number(q.owner_id)); if (q.customer_id) list = list.filter((o) => o.customer_id === Number(q.customer_id));
    if (q.q) { const s = q.q.toLowerCase(); list = list.filter((o) => [o.title, o.customer_name, o.customer_company].some((x) => String(x || '').toLowerCase().includes(s))); }
    if (q.tag) list = list.filter((o) => (o.tags || []).includes(q.tag) || (o.customer_tags || []).includes(q.tag)); if (q.source) list = list.filter((o) => (o.source || o.customer_source) === q.source); if (q.stage_id) list = list.filter((o) => o.stage_id === Number(q.stage_id)); if (q.open === 'true' || q.kind) list = list.filter((o) => o.stage_kind === (q.kind || 'open'));
    if (q.no_task === 'true') list = list.filter((o) => o.stage_kind === 'open' && !o.open_tasks && !o.next_action_at); if (q.overdue === 'true') list = list.filter((o) => o.stage_kind === 'open' && ((o.next_action_at && new Date(o.next_action_at) < Date.now()) || (o.next_task_at && new Date(o.next_task_at) < Date.now()))); if (q.idle_days) list = list.filter((o) => o.stage_kind === 'open' && new Date(o.updated_at) < Date.now() - Number(q.idle_days) * 86400000);
    if (q.sort) sortBy(list, q.sort === 'stage' ? 'stage_id' : q.sort === 'value' ? 'value' : q.sort, q.dir); else list.sort((a, b) => b.updated_at.localeCompare(a.updated_at)); list.forEach((o) => { o.value = Number(o.value); });
    const cutoff = Date.now() - 30 * 86400000; const out = q.all === 'true' ? list : list.filter((o) => o.stage_kind === 'open' || !o.closed_at || new Date(o.closed_at) >= cutoff);
    return { pipelines, pipeline_id: pid, stages: db.stages.filter((s) => s.active && (!pid || s.pipeline_id === pid)), opportunities: out, total: list.length }; });
  on('GET', '/opportunities/:id', (p) => { need(); const o = oppView(loadO(p.id)); return { opportunity: o, events: db.opportunity_events.filter((e) => e.opportunity_id === o.id).map((e) => ({ ...e, user_name: userName(e.user_id) })).reverse(), tasks: db.tasks.filter((t) => t.opportunity_id === o.id).map(taskView), tickets: db.tickets.filter((t) => t.customer_id === o.customer_id).slice(-6).reverse(), stages: db.stages.filter((s) => s.active && s.pipeline_id === o.pipeline_id) }; });
  on('POST', '/opportunities', (p, q, b) => { const u = need(); if (u.role === 'atendente' && b.owner_id && b.owner_id !== u.id) fail(403, 'Atendentes só podem criar oportunidades sob sua própria responsabilidade.'); const c = byId(db.customers, b.customer_id) || fail(400, 'Cliente não encontrado.', { fields: { customer_id: 'Cliente inválido.' } }); let st = b.stage_id ? stage(b.stage_id) : null; if (!st || !st.id) { const pid = b.pipeline_id || (db.pipelines.find((x) => x.active && x.is_default) || db.pipelines[0]).id; st = db.stages.find((s) => s.active && s.kind === 'open' && s.pipeline_id === pid); } if (!st || st.kind !== 'open') fail(400, 'Crie a oportunidade em uma etapa aberta.');
    const o = { id: nextId(db.opportunities), title: b.title, customer_id: c.id, owner_id: b.owner_id === undefined ? u.id : b.owner_id, stage_id: st.id, value: Number(b.value) || 0, next_action: b.next_action || null, next_action_at: b.next_action_at || null, expected_close_date: b.expected_close_date || null, lost_reason: null, ticket_id: b.ticket_id || null, closed_at: null, version: 1, created_by: u.id, created_at: now(), updated_at: now(), stage_entered_at: now(), tags: b.tags || [], source: b.source || c.source || null }; db.opportunities.push(o); oppEvent(o, `Oportunidade criada na etapa "${st.name}"`, { action: 'created' }); audit('opportunity_create', 'opportunity', o.id); return { opportunity: oppView(o), message: 'Oportunidade criada.' }; });
  on('PUT', '/opportunities/:id', (p, q, b) => { need(); const o = loadO(p.id); if (!isMgr() && o.owner_id !== user().id && o.owner_id != null) fail(403, 'Somente o responsável pode editar esta oportunidade.'); if (b.version !== undefined && b.version !== o.version) fail(409, 'Esta oportunidade foi alterada por outro usuário. Recarregue para ver a versão atual.'); if (b.stage_id !== undefined && b.stage_id !== o.stage_id) fail(400, 'Use a ação "mover etapa" para alterar a etapa.'); const L = { title: 'título', owner_id: 'responsável', value: 'valor', next_action: 'próxima ação', next_action_at: 'data da próxima ação', expected_close_date: 'previsão', tags: 'etiquetas', source: 'origem' }; const changed = Object.keys(b).filter((k) => L[k] && JSON.stringify(b[k]) !== JSON.stringify(o[k])); changed.forEach((k) => { o[k] = k === 'value' ? Number(b[k]) : b[k]; }); o.version++; o.updated_at = now(); if (changed.length) oppEvent(o, `Campos atualizados: ${changed.map((k) => L[k]).join(', ')}`, { action: 'updated' }); audit('opportunity_update', 'opportunity', o.id); return { opportunity: oppView(o), message: 'Oportunidade atualizada.' }; });
  on('POST', '/opportunities/:id/move', (p, q, b) => { need(); const o = loadO(p.id); if (!isMgr() && o.owner_id !== user().id && o.owner_id != null) fail(403, 'Somente o responsável pode mover esta oportunidade.'); if (b.version !== undefined && b.version !== o.version) fail(409, 'Esta oportunidade foi alterada por outro usuário. Recarregue para ver a versão atual.'); const st = stage(b.stage_id); if (!st.id || !st.active) fail(400, 'Etapa inválida.'); if (st.pipeline_id !== stage(o.stage_id).pipeline_id) fail(400, 'A etapa pertence a outro funil.'); if (st.id === o.stage_id) return { opportunity: oppView(o), message: 'Etapa atualizada.' }; if (st.kind === 'lost' && !b.lost_reason) fail(400, 'Informe o motivo da perda.', { fields: { lost_reason: 'Motivo obrigatório.' }, requires_lost_reason: true }); const from = stage(o.stage_id).name; o.stage_id = st.id; o.closed_at = st.kind === 'open' ? null : now(); o.lost_reason = st.kind === 'lost' ? b.lost_reason : null; o.stage_entered_at = now(); o.version++; o.updated_at = now(); oppEvent(o, `Movida de "${from}" para "${st.name}"${st.kind === 'lost' ? ` — motivo: ${b.lost_reason}` : ''}`, { action: 'move' }); if (st.kind !== 'open') stopFollowUps((x) => x.opportunity_id === o.id, 'Negociação encerrada'); audit('opportunity_move', 'opportunity', o.id); runRules('opportunity_stage_changed', 'opportunity', o.id, `stage:${st.id}:${Date.now()}`); return { opportunity: oppView(o), message: 'Etapa atualizada.' }; });
  on('DELETE', '/opportunities/:id', (p) => { requireRole('admin', 'supervisor'); const o = loadO(p.id); db.opportunities = db.opportunities.filter((x) => x.id !== o.id); audit('opportunity_delete', 'opportunity', o.id); return { ok: true, message: 'Oportunidade excluída.' }; });

  const scopeK = (t) => isMgr() || t.assignee_id === user().id || t.created_by === user().id;
  on('GET', '/tasks', (p, q) => { need(); const all = db.tasks.filter(scopeK); const today = new Date().toDateString(); const isT = (d) => d && new Date(d).toDateString() === today; const V = { today: (t) => !t.done_at && isT(t.due_at), upcoming: (t) => !t.done_at && t.due_at && new Date(t.due_at) > new Date() && !isT(t.due_at), overdue: (t) => !t.done_at && t.due_at && new Date(t.due_at) < Date.now(), open: (t) => !t.done_at, done: (t) => !!t.done_at, all: () => true }; let list = all.filter(V[q.view] || V.all); if (q.assignee_id) list = list.filter((t) => t.assignee_id === Number(q.assignee_id)); if (q.customer_id) list = list.filter((t) => t.customer_id === Number(q.customer_id)); list = list.map(taskView).sort((a, b) => ((a.done_at ? 1 : 0) - (b.done_at ? 1 : 0)) || (a.due_at || 'z').localeCompare(b.due_at || 'z')); return { tasks: list.slice(0, Number(q.limit) || 500), summary: { today: all.filter(V.today).length, upcoming: all.filter(V.upcoming).length, overdue: all.filter(V.overdue).length, open: all.filter(V.open).length } }; });
  on('POST', '/tasks', (p, q, b) => { const u = need(); if (!isMgr() && b.assignee_id && b.assignee_id !== u.id) fail(403, 'Atendentes não podem atribuir tarefas a outros usuários.'); const t = { id: nextId(db.tasks), title: b.title, description: b.description || null, customer_id: b.customer_id || null, opportunity_id: b.opportunity_id || null, ticket_id: b.ticket_id || null, assignee_id: b.assignee_id === undefined ? u.id : b.assignee_id, due_at: b.due_at || null, priority: b.priority || 'normal', done_at: null, kind: 'tarefa', automation_rule_id: null, created_by: u.id, created_at: now(), updated_at: now() }; db.tasks.push(t); if (t.assignee_id && t.assignee_id !== u.id) notify(t.assignee_id, 'Nova tarefa atribuída', t.title, '#/tarefas'); audit('task_create', 'task', t.id); return { task: taskView(t), message: 'Tarefa criada.' }; });
  on('PUT', '/tasks/:id', (p, q, b) => { need(); const t = byId(db.tasks, p.id); if (!t || !scopeK(t)) fail(404, 'Tarefa não encontrada ou fora do seu escopo.'); if (!isMgr() && b.assignee_id != null && b.assignee_id !== user().id) fail(403, 'Atendentes não podem atribuir tarefas a outros usuários.'); if (b.done !== undefined) { t.done_at = b.done ? now() : null; if (!b.done) t.closed_reason = null; } ['title', 'description', 'customer_id', 'opportunity_id', 'assignee_id', 'due_at', 'priority'].forEach((k) => { if (b[k] !== undefined) t[k] = b[k]; }); t.updated_at = now(); return { task: taskView(t), message: b.done === true ? 'Tarefa concluída.' : b.done === false ? 'Tarefa reaberta.' : 'Tarefa atualizada.' }; });
  on('DELETE', '/tasks/:id', (p) => { need(); const t = byId(db.tasks, p.id); if (!t || !scopeK(t)) fail(404); db.tasks = db.tasks.filter((x) => x.id !== t.id); return { ok: true, message: 'Tarefa excluída.' }; });

  on('GET', '/reports/dashboard', () => dashboard());
  on('GET', '/reports/summary', (p, q) => summary(q));
  on('GET', '/reports/export.csv', (p, q) => { const s = summary(q); return { csv: csv(s.by_assignee, [['name', 'responsavel'], ['total', 'total'], ['open', 'abertos'], ['resolved', 'resolvidos']]), filename: 'relatorio-atendimentos.csv' }; });
  on('GET', '/notifications', () => { const u = need(); const list = db.notifications.filter((n) => n.user_id === u.id).slice(0, 50); return { notifications: list, unread: list.filter((n) => !n.read_at).length, alerts: { overdue_tasks: db.tasks.filter((t) => t.assignee_id === u.id && !t.done_at && t.due_at && new Date(t.due_at) < Date.now()).length, follow_ups_due: db.tickets.filter((t) => t.assignee_id === u.id && t.follow_up_at && new Date(t.follow_up_at) <= Date.now() + 86400000 && OPEN.includes(t.status)).length } }; });
  on('POST', '/notifications/read-all', () => { const u = need(); db.notifications.filter((n) => n.user_id === u.id).forEach((n) => { n.read_at = n.read_at || now(); }); return { ok: true }; });
  on('POST', '/notifications/:id/read', (p) => { const n = byId(db.notifications, p.id); if (n) n.read_at = now(); return { ok: true }; });

  on('GET', '/quick-replies', (p, q) => { const u = need(); const all = q.all === 'true' && u.role !== 'atendente'; return { quick_replies: db.quick_replies.filter((x) => all || x.active).map((x) => ({ ...x, created_by_name: userName(x.created_by) })) }; });
  on('POST', '/quick-replies', (p, q, b) => { requireRole('admin', 'supervisor'); const x = { id: nextId(db.quick_replies), title: b.title, shortcut: b.shortcut || null, body: b.body, active: b.active !== false, created_by: user().id, created_at: now(), updated_at: now() }; db.quick_replies.push(x); return { quick_reply: x, message: 'Resposta rápida criada.' }; });
  on('PUT', '/quick-replies/:id', (p, q, b) => { requireRole('admin', 'supervisor'); const x = byId(db.quick_replies, p.id) || fail(404); Object.assign(x, b, { updated_at: now() }); return { quick_reply: x, message: 'Resposta rápida atualizada.' }; });
  on('DELETE', '/quick-replies/:id', (p) => { requireRole('admin', 'supervisor'); db.quick_replies = db.quick_replies.filter((x) => x.id !== Number(p.id)); return { ok: true, message: 'Resposta rápida excluída.' }; });
  on('GET', '/saved-filters', (p, q) => { const u = need(); return { filters: db.saved_filters.filter((f) => (f.user_id === u.id || f.shared) && (!q.scope || f.scope === q.scope)).map((f) => ({ ...f, user_name: userName(f.user_id) })) }; });
  on('POST', '/saved-filters', (p, q, b) => { const u = need(); const f = { id: nextId(db.saved_filters), user_id: u.id, scope: b.scope, name: b.name, params: b.params || {}, shared: Boolean(b.shared) && isMgr(), created_at: now() }; db.saved_filters.push(f); return { filter: f, message: 'Filtro salvo.' }; });
  on('DELETE', '/saved-filters/:id', (p) => { need(); const f = byId(db.saved_filters, p.id) || fail(404); if (f.user_id !== user().id && !isMgr()) fail(403); db.saved_filters = db.saved_filters.filter((x) => x.id !== f.id); return { ok: true, message: 'Filtro removido.' }; });

  on('GET', '/settings/pipelines', () => { need(); return { pipelines: db.pipelines.map((p) => ({ ...p, stages: db.stages.filter((s) => s.pipeline_id === p.id) })) }; });
  on('POST', '/settings/pipelines', (p, q, b) => { requireRole('admin'); const pl = { id: nextId(db.pipelines), name: b.name, position: db.pipelines.length + 1, is_default: false, active: true, created_at: now() }; db.pipelines.push(pl); [['Novo contato', 'open'], ['Qualificação', 'open'], ['Proposta', 'open'], ['Negociação', 'open'], ['Ganho', 'won'], ['Perdido', 'lost']].forEach(([n, k], i) => db.stages.push({ id: nextId(db.stages), pipeline_id: pl.id, name: n, kind: k, position: i + 1, active: true, color: null })); return { pipeline: pl, message: 'Funil criado com etapas padrão.' }; });
  on('PUT', '/settings/pipelines/:id', (p, q, b) => { requireRole('admin'); const pl = byId(db.pipelines, p.id) || fail(404, 'Funil não encontrado.'); if (b.active === false) { if (!db.pipelines.some((x) => x.active && x.id !== pl.id)) fail(400, 'Mantenha ao menos um funil ativo.'); if (pl.is_default) fail(400, 'Defina outro funil como padrão antes de desativar este.'); } if (b.is_default) db.pipelines.forEach((x) => { x.is_default = false; }); Object.assign(pl, b); return { pipeline: pl, message: 'Funil atualizado.' }; });
  on('GET', '/settings/stages', (p, q) => { need(); return { stages: db.stages.filter((s) => !q.pipeline_id || s.pipeline_id === Number(q.pipeline_id)) }; });
  on('PUT', '/settings/stages', (p, q, b) => { requireRole('admin'); const act = b.stages.filter((s) => s.active !== false); if (act.filter((s) => s.kind === 'won').length !== 1 || act.filter((s) => s.kind === 'lost').length !== 1) fail(400, 'O funil precisa ter exatamente uma etapa "Ganho" e uma etapa "Perdido" ativas.'); const pid = b.pipeline_id || (db.pipelines.find((x) => x.is_default) || db.pipelines[0]).id; const keep = new Set(); b.stages.forEach((s, i) => { let st = s.id ? byId(db.stages, s.id) : null; if (!st) { st = { id: nextId(db.stages), pipeline_id: pid }; db.stages.push(st); } Object.assign(st, { name: s.name, kind: s.kind, color: s.color || null, active: s.active !== false, position: i + 1 }); keep.add(st.id); }); db.stages.filter((s) => s.pipeline_id === pid && !keep.has(s.id)).forEach((s) => { if (db.opportunities.some((o) => o.stage_id === s.id)) { s.active = false; s.position = 999; } else db.stages = db.stages.filter((x) => x.id !== s.id); }); return { stages: db.stages.filter((s) => s.pipeline_id === pid), message: 'Etapas do funil atualizadas.' }; });
  on('GET', '/settings/audit', (p, q) => { requireRole('admin', 'supervisor'); let l = db.audit.map((a) => ({ ...a, user_name: a.user_name || userName(a.user_id) })); if (q.user_id) l = l.filter((a) => a.user_id === Number(q.user_id)); if (q.action) l = l.filter((a) => a.action.includes(q.action)); return { entries: l.slice(0, Number(q.limit) || 100) }; });

  const TRIGGERS = { ticket_created: { label: 'Atendimento aberto', entity: 'ticket', conditions: ['channel', 'priority', 'team'] }, ticket_customer_replied: { label: 'Cliente respondeu', entity: 'ticket', conditions: ['channel', 'team'] }, ticket_response_overdue: { label: 'Prazo de resposta vencido', entity: 'ticket', conditions: ['minutes', 'priority', 'team'] }, ticket_follow_up_overdue: { label: 'Retorno agendado vencido', entity: 'ticket', conditions: ['minutes', 'team'] }, opportunity_stage_changed: { label: 'Oportunidade mudou de etapa', entity: 'opportunity', conditions: ['stage_id', 'team'] }, opportunity_idle: { label: 'Oportunidade parada', entity: 'opportunity', conditions: ['days', 'pipeline_id', 'team'] } };
  const ACTIONS = { create_task: { label: 'Criar tarefa' }, notify: { label: 'Notificar' }, distribute: { label: 'Distribuir em rodízio' }, set_priority: { label: 'Alterar prioridade' }, add_tag: { label: 'Adicionar etiqueta ao cliente' }, send_message: { label: 'Enviar mensagem (canal conectado)' } };
  on('GET', '/automations/meta', () => { requireRole('admin', 'supervisor'); return { triggers: TRIGGERS, actions: ACTIONS, whatsapp_connected: false }; });
  on('GET', '/automations/runs', (p, q) => { requireRole('admin', 'supervisor'); return { runs: db.automation_runs.filter((x) => !q.rule_id || x.rule_id === Number(q.rule_id)).slice(0, Number(q.limit) || 100).map((x) => { const r = byId(db.automation_rules, x.rule_id) || {}; const t = x.entity === 'ticket' ? byId(db.tickets, x.entity_id) : byId(db.opportunities, x.entity_id); return { ...x, rule_name: r.name, entity_label: t ? (t.protocol || t.title) : null }; }) }; });
  on('GET', '/automations', () => { requireRole('admin', 'supervisor'); const w = Date.now() - 7 * 86400000; return { rules: db.automation_rules.map((r) => ({ ...r, created_by_name: userName(r.created_by), runs_7d: db.automation_runs.filter((x) => x.rule_id === r.id && x.status === 'executada' && new Date(x.created_at) > w).length, failures_7d: db.automation_runs.filter((x) => x.rule_id === r.id && x.status === 'falhou' && new Date(x.created_at) > w).length })) }; });
  const checkRule = (d) => { if (d.action === 'send_message') fail(400, 'Mensagens automáticas exigem um canal conectado. O WhatsApp está desconectado nesta demonstração.'); if (['distribute', 'set_priority'].includes(d.action) && TRIGGERS[d.trigger].entity !== 'ticket') fail(400, 'Esta ação só se aplica a gatilhos de atendimento.'); if (d.action === 'create_task' && !d.action_params.title) fail(400, 'Informe o título da tarefa.', { fields: { 'action_params.title': 'Obrigatório.' } }); };
  on('POST', '/automations', (p, q, b) => { requireRole('admin', 'supervisor'); checkRule(b); const r = { id: nextId(db.automation_rules), name: b.name, trigger: b.trigger, conditions: b.conditions || {}, action: b.action, action_params: b.action_params || {}, team: b.team || null, active: b.active !== false, last_run_at: null, runs_count: 0, created_by: user().id, created_at: now(), updated_at: now() }; db.automation_rules.push(r); audit('automation_create', 'automation_rule', r.id); return { rule: r, message: 'Regra criada.' }; });
  on('PUT', '/automations/:id', (p, q, b) => { requireRole('admin', 'supervisor'); const r = byId(db.automation_rules, p.id) || fail(404, 'Regra não encontrada.'); const d = { ...r, ...b }; checkRule(d); Object.assign(r, d, { updated_at: now() }); return { rule: r, message: b.active === false ? 'Regra pausada.' : b.active === true ? 'Regra ativada.' : 'Regra atualizada.' }; });
  on('DELETE', '/automations/:id', (p) => { requireRole('admin', 'supervisor'); db.automation_rules = db.automation_rules.filter((x) => x.id !== Number(p.id)); db.automation_runs = db.automation_runs.filter((x) => x.rule_id !== Number(p.id)); return { ok: true, message: 'Regra excluída.' }; });
  on('POST', '/automations/run-scheduled', () => { requireRole('admin', 'supervisor'); runScheduled(); return { ok: true, message: 'Verificação executada.' }; });

  on('GET', '/whatsapp/status', () => { need(); return { connected: false, state: 'desconectado', phone_number_id: null, webhook_url: 'https://SEU-SERVIDOR/api/whatsapp/webhook', webhook_ready: false, signature_check: false, missing: ['WHATSAPP_TOKEN', 'WHATSAPP_PHONE_NUMBER_ID', 'WHATSAPP_VERIFY_TOKEN', 'WHATSAPP_APP_SECRET'], last_event_at: null, last_error: null, last_error_at: null, stats: { received: 0, sent: 0, failed: 0 }, pending: ['Esta é a demonstração estática (GitHub Pages): não há servidor para receber webhooks nem credenciais. Na instalação com servidor, configure WHATSAPP_TOKEN e WHATSAPP_PHONE_NUMBER_ID.'], message: 'Integração desconectada. Enquanto as credenciais não forem configuradas no servidor, use "Abrir no WhatsApp" (atalho externo) e registre a interação manualmente.' }; });
  on('GET', '/whatsapp/window/:id', () => ({ connected: false, open: false, last_inbound_at: null }));
  on('POST', '/whatsapp/send', () => fail(503, 'WhatsApp não está conectado nesta demonstração. Registre a interação manualmente.'));
  on('GET', '/whatsapp/log', () => { requireRole('admin', 'supervisor'); return { messages: [] }; });

  // ---------- Despacho ----------
  window.api = async function api(path, { method = 'GET', body, query } = {}) {
    const [rawPath, qs] = path.split('?');
    const q = { ...Object.fromEntries(new URLSearchParams(qs || '')) };
    Object.entries(query || {}).forEach(([k, v]) => { if (v !== undefined && v !== null && v !== '') q[k] = String(v); });
    await new Promise((r) => setTimeout(r, 40));
    const route = R.find((r) => r.method === method && r.re.test(rawPath));
    if (!route) throw new ApiError(404, { error: 'Rota não encontrada na demonstração.' });
    try {
      const params = rawPath.match(route.re).groups || {};
      const out = route.fn(params, q, clone(body || {}));
      if (method !== 'GET') save();
      return clone(out);
    } catch (e) {
      if (e instanceof ApiError) { if (e.status === 401 && window.CRM && CRM.onUnauthorized) CRM.onUnauthorized(); throw e; }
      console.error(e); throw new ApiError(500, { error: 'Erro na demonstração: ' + e.message });
    }
  };
  window.ApiError = ApiError;
  window.DEMO_RESET = () => { localStorage.removeItem(KEY); sessionStorage.removeItem('crm.demo.user'); location.reload(); };
  window.addEventListener('DOMContentLoaded', () => { setInterval(() => { if (user()) { runScheduled(); save(); } }, 60000); });
})();
